plugins:
  - jekyll-relative-links
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
search: true
search_full_content: true
# breadcrumbs: true
include:
  - CONTRIBUTING.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/the-bachelor-brothers/software-engineering-notes"

repository: "the-bachelor-brothers/software-engineering-notes"

remote_theme: "mmistakes/minimal-mistakes"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: true
      sidebar:
        nav: "docs"
